/**
 * Semantic media keys -> file paths. Swapping a placeholder for a real asset is a
 * one-line path change here; nothing else in the site references image files directly.
 * Placeholders are generated by `pnpm gen:placeholders` (scripts/gen-placeholders.mjs).
 */
const P = "/placeholders";

export const media = {
  // Projects (key pattern: projects.<slug>.cover, gallery.<name>).
  // Covers are the nonprofit logos for now; the gallery is still placeholder screenshots.
  "projects.sheltering-wings.cover": "/images/projects/sheltering-wings/cover.jpg",
  "projects.share-food-share-love.cover": "/images/projects/share-food-share-love/cover.jpg",
  "projects.midtown-family-services.cover": "/images/projects/midtown-family-services/cover.jpg",
  "projects.mill-creek-urban-farm.cover": "/images/projects/mill-creek-urban-farm/cover.jpg",
  "projects.sleep-pod.cover": "/images/projects/sleep-pod/cover.jpg",
  "projects.pratigya.cover": "/images/projects/pratigya/cover.jpg",
  "projects.vpwa.cover": "/images/projects/vpwa/cover.jpg",
  "projects.we-the-world-botswana.cover": "/images/projects/we-the-world-botswana/cover.jpg",
  "gallery.placeholder-1": `${P}/gallery-1.svg`,
  "gallery.placeholder-2": `${P}/gallery-2.svg`,
  "gallery.placeholder-3": `${P}/gallery-3.svg`,

  // Organization and awards (home hero, About mission photo, Impact awards carousel)
  "org.hero-photo": "/images/home/hero.jpg",
  "org.group-photo": "/images/home/group-photo.jpg",
  "awards.student-life-2025.1": "/images/awards/student-life-innovative-program-2025/1.jpg",
  "awards.student-life-2025.2": "/images/awards/student-life-innovative-program-2025/2.jpg",
  "awards.student-life-2025.3": "/images/awards/student-life-innovative-program-2025/3.jpg",

  // Home "What we do" panels, then club life (also /students How we work and What you'll get)
  "home.what-we-do.free-software": "/images/home/what-we-do-free-software.jpg",
  "life.students": "/images/life/students.jpg",
  "life.kickoff": "/images/life/kickoff.jpg",
  "life.team-table": "/images/life/team-table.jpg",
  "life.social-atrium": "/images/life/social-atrium.jpg",
  "life.puzzle-night": "/images/life/puzzle-night.jpg",
  "life.team-selfie": "/images/life/team-selfie.jpg",

  // Instagram grid on /about (key pattern: instagram.<post id>); four ornament variants.
  "instagram.post-1": `${P}/instagram-globe.svg`,
  "instagram.post-2": `${P}/instagram-checker.svg`,
  "instagram.post-3": `${P}/instagram-zigzag.svg`,
  "instagram.post-4": `${P}/instagram-brackets.svg`,
  "instagram.post-5": `${P}/instagram-checker.svg`,
  "instagram.post-6": `${P}/instagram-globe.svg`,

  // People (key pattern: exec.<slug>, the slug carrying the board year)
  "exec.arav-shah-2026": "/images/exec/arav-shah-2026.jpeg",
  "exec.emily-li-2026": "/images/exec/emily-li-2026.jpg",
  "exec.arushi-ravula-2026": "/images/exec/arushi-ravula-2026.jpg",
  "exec.jason-gottesman-2026": "/images/exec/jason-gottesman-2026.jpg",
  "exec.ben-connelly-2026": "/images/exec/ben-connelly-2026.jpg",
  "exec.ashton-sun-2026": "/images/exec/ashton-sun-2026.jpg",
  "exec.khang-nguyen-2026": "/images/exec/khang-nguyen-2026.jpg",
  "exec.shreeya-sarurkar-2026": "/images/exec/shreeya-sarurkar-2026.jpg",
  "exec.nakul-naik-2026": "/images/exec/nakul-naik-2026.jpg",
  "exec.tanay-gondil-2025": "/images/exec/tanay-gondil-2025.jpg",
  "exec.mahika-parakh-2025": "/images/exec/mahika-parakh-2025.jpg",
  "exec.lalitha-chandolu-2025": "/images/exec/lalitha-chandolu-2025.jpg",
  "exec.devansh-khandelwal-2025": "/images/exec/devansh-khandelwal-2025.jpg",
  "exec.ryan-erickson-2025": "/images/exec/ryan-erickson-2025.jpg",
  "exec.vipula-shirse-2025": "/images/exec/vipula-shirse-2025.jpg",
  "exec.seth-parent-2025": "/images/exec/seth-parent-2025.jpg",
  "exec.arushi-ravula-2025": "/images/exec/arushi-ravula-2025.jpg",
  "exec.emily-li-2025": "/images/exec/emily-li-2025.jpg",
  "exec.youngjun-yoo-2025": "/images/exec/youngjun-yoo-2025.jpg",
  "avatar.placeholder": `${P}/avatar.svg`,
} as const satisfies Record<string, string>;

export type MediaKey = keyof typeof media;

export function isMediaKey(value: string): value is MediaKey {
  return Object.prototype.hasOwnProperty.call(media, value);
}

/** Resolve a media key to its path. Direct paths (starting with "/" or "http") pass through. */
export function mediaSrc(keyOrPath: string): string {
  if (isMediaKey(keyOrPath)) return media[keyOrPath];
  if (keyOrPath.startsWith("/") || /^https?:\/\//.test(keyOrPath)) return keyOrPath;
  throw new Error(
    `Unknown media key "${keyOrPath}". Add it to content/media.ts or use a /public path.`,
  );
}
