/**
 * Semantic media keys -> file paths. Swapping a placeholder for a real asset is a
 * one-line path change here; nothing else in the site references image files directly.
 * Placeholders are generated by `pnpm gen:placeholders` (scripts/gen-placeholders.mjs).
 */
const P = "/placeholders";

export const media = {
  // Brand / sharing
  "og.default": `${P}/og.svg`,

  // Projects (key pattern: projects.<slug>.cover, gallery.<name>)
  "projects.placeholder-project-1.cover": `${P}/cover-16x9.svg`,
  "projects.placeholder-project-2.cover": `${P}/cover-4x5.svg`,
  "projects.placeholder-project-3.cover": `${P}/cover-16x9.svg`,
  "gallery.placeholder-1": `${P}/gallery-16x10.svg`,
  "gallery.placeholder-2": `${P}/gallery-16x10.svg`,

  // People (key pattern: exec.<slug>)
  "exec.todo-president": `${P}/exec.svg`,
  "exec.ashton-sun": `${P}/exec.svg`,
  "exec.todo-exec-3": `${P}/exec.svg`,
  "avatar.placeholder": `${P}/avatar.svg`,
} as const satisfies Record<string, string>;

export type MediaKey = keyof typeof media;

export function isMediaKey(value: string): value is MediaKey {
  return Object.prototype.hasOwnProperty.call(media, value);
}

/** Resolve a media key to its path. Direct paths (starting with "/" or "http") pass through. */
export function mediaSrc(keyOrPath: string): string {
  if (isMediaKey(keyOrPath)) return media[keyOrPath];
  if (keyOrPath.startsWith("/") || /^https?:\/\//.test(keyOrPath)) return keyOrPath;
  throw new Error(
    `Unknown media key "${keyOrPath}". Add it to content/media.ts or use a /public path.`,
  );
}
