"""
Generate src/components/brand/logo-paths.ts from the Cunia typeface outlines.

Usage:  python scripts/gen-logo-paths.py
Needs:  pip install fonttools   (reads reference/branding/Fonts/Cunia.zip directly)

The <HTF/> wordmark is composed from six Cunia glyphs (< H T F / >). Letters are
emitted with role "letter" (primary green) and the brackets/slash with role "mark"
(secondary green), matching the Instagram graphics. Coordinates are font units
(1000/em), y-up; the Logo component applies the y-flip.
"""
from __future__ import annotations

import io
import json
import re
import zipfile
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
ZIP = ROOT / "reference/branding/Fonts/Cunia.zip"
OUT = ROOT / "src/components/brand/logo-paths.ts"

CAP = 700  # Cunia cap height in font units
SEQ = "<HTF/>"
TRACKING = -30  # tighten every pair a little
PAIR_ADJUST = {"<": -70, "F": -30, "/": -60}  # extra pull after these glyphs
SCALE_TO = {"<": (0, 700), ">": (0, 700), "/": (-20, 720)}  # vertical span targets

NUM = r"-?(?:\d+\.?\d*|\.\d+)(?:e-?\d+)?"
ARGC = {"M": 2, "L": 2, "H": 1, "V": 1, "Q": 4, "C": 6, "T": 2, "S": 4, "Z": 0}


def parse_abs(d: str):
    """Parse an absolute-only SVG path (what fontTools emits) into (cmd, [x,y,...]) with H/V expanded to L."""
    tokens = re.findall(rf"[A-Za-z]|{NUM}", d)
    out, i, cur, cx, cy, sx, sy = [], 0, None, 0.0, 0.0, 0.0, 0.0
    while i < len(tokens):
        t = tokens[i]
        if t.isalpha():
            cur = t.upper()
            i += 1
            if cur == "Z":
                out.append(("Z", []))
                cx, cy = sx, sy
            continue
        n = ARGC[cur]
        nums = [float(x) for x in tokens[i : i + n]]
        i += n
        if cur == "H":
            cx = nums[0]
            out.append(("L", [cx, cy]))
        elif cur == "V":
            cy = nums[0]
            out.append(("L", [cx, cy]))
        else:
            out.append((cur, nums))
            cx, cy = nums[-2], nums[-1]
            if cur == "M":
                sx, sy = cx, cy
    return out


def emit(cmds, fx, fy) -> str:
    parts = []
    for c, nums in cmds:
        if c == "Z":
            parts.append("Z")
            continue
        pts = [(fx(nums[k]), fy(nums[k + 1])) for k in range(0, len(nums), 2)]
        parts.append(c + " ".join(f"{x:.0f} {y:.0f}" for x, y in pts))
    return "".join(parts)


def main() -> None:
    ttf = zipfile.ZipFile(ZIP).read("Cunia.ttf")
    font = TTFont(io.BytesIO(ttf))
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()

    x = 0.0
    glyphs = []
    for ch in SEQ:
        g = gs[cmap[ord(ch)]]
        pen, bp = SVGPathPen(gs), BoundsPen(gs)
        g.draw(pen)
        g.draw(bp)
        x0, y0, x1, y1 = bp.bounds
        s = 1.0
        dy = 0.0
        if ch in SCALE_TO:
            t0, t1 = SCALE_TO[ch]
            s = (t1 - t0) / (y1 - y0)
            dy = t0 - y0 * s  # y' = y*s + dy  maps y0 -> t0
        # x' = (x - x0)*s + x0 + x   (scale about the glyph's left edge, then place)
        fx = lambda v, s=s, x0=x0, x=x: (v - x0) * s + x0 + x
        fy = lambda v, s=s, dy=dy: v * s + dy
        d = emit(parse_abs(pen.getCommands()), fx, fy)
        adv = g.width * s
        glyphs.append({"ch": ch, "role": "letter" if ch in "HTF" else "mark", "d": d})
        x += adv + TRACKING + PAIR_ADJUST.get(ch, 0)
    width = x - TRACKING
    lines = [
        "// Generated by scripts/gen-logo-paths.py from the Cunia typeface outlines",
        "// (reference/branding/Fonts/Cunia.zip). Font units (1000/em), y-up; the Logo",
        "// component flips y. Do not hand-edit; re-run the script to regenerate.",
        "",
        f"export const LOGO_WIDTH = {width:.0f};",
        f"export const LOGO_CAP = {CAP};",
        "export const LOGO_TOP = 720; // highest point (slash) above the baseline",
        "export const LOGO_BOTTOM = -20; // lowest point (slash) below the baseline",
        "",
        "export type LogoGlyph = { ch: string; role: \"mark\" | \"letter\"; d: string };",
        "",
        "export const LOGO_GLYPHS: LogoGlyph[] = [",
    ]
    for gl in glyphs:
        lines.append(f"  {{ ch: {json.dumps(gl['ch'])}, role: \"{gl['role']}\", d: {json.dumps(gl['d'])} }},")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} (width {width:.0f})")


if __name__ == "__main__":
    main()
