import { sphericalToVector } from "@/lib/geo";

/**
 * Land dots for the three.js globe, read from the dotted world map the site already ships
 * (public/maps/world-dots.svg, generated by scripts/gen-world-dots.mjs). The SVG encodes
 * each row of land as horizontal runs of a dashed path, so the grid can be recovered from
 * the run endpoints; the constants below must match the generator. Fetched once, on demand.
 */

const STEP = 1.25; // degrees between dots
const LAT_MAX = 84;
const PITCH = 4; // SVG units between dot centres
const RADIUS = 1.003; // just above the wireframe sphere

let cache: Promise<Float32Array> | null = null;

export function loadLandDots(): Promise<Float32Array> {
  cache ??= fetch("/maps/world-dots.svg")
    .then((res) => (res.ok ? res.text() : Promise.reject(new Error(`HTTP ${res.status}`))))
    .then(parseDots);
  return cache;
}

/** xyz triples on the sphere for every dot in the path. */
export function parseDots(svg: string): Float32Array {
  const d = /\sd="([^"]+)"/.exec(svg)?.[1] ?? "";
  const out: number[] = [];
  const run = /M([\d.]+) ([\d.]+)(?:H([\d.]+)|h0\.01)/g;
  for (const match of d.matchAll(run)) {
    const x1 = Number(match[1]);
    const y = Number(match[2]);
    const x2 = match[3] === undefined ? x1 : Number(match[3]);
    const lat = LAT_MAX - (y / PITCH) * STEP;
    for (let x = x1; x <= x2 + 1e-6; x += PITCH) {
      const lng = -180 + (x / PITCH) * STEP;
      out.push(...sphericalToVector(lat, lng, RADIUS));
    }
  }
  return new Float32Array(out);
}
