import { cn } from "@/lib/utils";

type DottedMapProps = {
  /** Class for the map box: where it sits, how wide it is, any fade mask over the whole thing. */
  className?: string;
  /** Class for the land dots, e.g. their opacity. */
  dotsClassName?: string;
  /** Dot colour token. */
  tone?: "green" | "text";
  /** Tint the countries HTF has worked in, drawn over the land dots. */
  partners?: boolean;
  /** Class for the partner-country dots, e.g. their opacity. */
  partnersClassName?: string;
};

/**
 * The dot colour, as a flat gradient rather than a background colour: axe cannot see a mask,
 * so it would read a solid colour as a sheet over the whole map box and fail the thin-glass
 * cards above it (the Impact band) on contrast they pass on screen. An image background makes
 * it list them for review instead (2026-09-11: the brightest pixel behind their text gives
 * 7.2:1 for green, 6.5:1 for muted).
 */
const FILL = {
  green: "bg-[linear-gradient(var(--green),var(--green))]",
  text: "bg-[linear-gradient(var(--text),var(--text))]",
};

/**
 * Dot-matrix world map, the motif behind the Framer testimonial band and the
 * "8 Final Nonprofits" Instagram graphic. `public/maps/world-dots.svg` (generated by
 * scripts/gen-world-dots.mjs, 1152×456) is applied as a CSS mask over a solid colour, so the
 * dots take any brand token and the DOM stays at two elements. `partners` adds a third: the
 * same grid masked by world-dots-partners.svg, the dots of the countries a project has run in,
 * green over the land dots. Decorative: always hidden from assistive tech.
 */
export function DottedMap({
  className,
  dotsClassName,
  tone = "green",
  partners = false,
  partnersClassName,
}: DottedMapProps) {
  return (
    <div
      aria-hidden="true"
      className={cn("pointer-events-none relative aspect-[1152/456] w-full select-none", className)}
    >
      <div
        className={cn(
          "size-full mask-[url(/maps/world-dots.svg)] mask-contain mask-center mask-no-repeat",
          tone === "green" ? FILL.green : FILL.text,
          dotsClassName,
        )}
      />
      {partners ? (
        <div
          className={cn(
            "absolute inset-0 mask-[url(/maps/world-dots-partners.svg)] mask-contain mask-center mask-no-repeat",
            FILL.green,
            partnersClassName,
          )}
        />
      ) : null}
    </div>
  );
}
