import { cn } from "@/lib/utils";

type DottedMapProps = {
  className?: string;
  /** Dot colour token. */
  tone?: "green" | "text";
};

/**
 * Dot-matrix world map, the motif behind the Framer testimonial band and the
 * "8 Final Nonprofits" Instagram graphic. `public/maps/world-dots.svg` (generated by
 * scripts/gen-world-dots.mjs, 1152×456) is applied as a CSS mask over a solid colour, so the
 * dots take any brand token and the DOM stays at two elements. Decorative: always hidden
 * from assistive tech.
 */
export function DottedMap({ className, tone = "green" }: DottedMapProps) {
  return (
    <div
      aria-hidden="true"
      className={cn("pointer-events-none aspect-[1152/456] w-full select-none", className)}
    >
      <div
        className={cn(
          "size-full mask-[url(/maps/world-dots.svg)] mask-contain mask-center mask-no-repeat",
          tone === "green" ? "bg-green" : "bg-text",
        )}
      />
    </div>
  );
}
